name: linux-ci

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "include/**"
      - ".github/workflows/linux-ci.yml"
      - "vendor/**"
      - "CMakeLists.txt"
      - metrics/linux-gcc8-release-style.json

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # INFO: We are cancelling the concurrency group if the change is on PR. For workflow dispatch, this will not work.
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Get ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ env.cache-name }}-${{ runner.os }}-${{ github.job }}-${{ github.ref }}-${{ github.sha }}-${{ github.head_ref }}

      - name: Get latest CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 3.24.1
          ninjaVersion: latest

      - name: Clear ccache
        run: ccache --clear

      - name: Save and restore ccache keys
        uses: actions/cache@v3
        env:
          cache-name: ccache-maplibre-core
        with:
          path: ~/.ccache
          key: ${{ env.cache-name }}-${{ runner.os }}-${{ github.job }}-${{ github.ref }}-${{ github.sha }}-${{ github.head_ref }}
          # INFO: No fallback restore. Only restoring keys that have the same github reference. Rerunning the same workflow
          # will be faster. New workflow invocation with different code, sha1, or head will not be.

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libuv1-dev \
            libjpeg-dev \
            libpng-dev \
            libglfw3-dev

      - name: Build Maplibre GL Core
        run: |
          cmake --version
          cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DMBGL_WITH_COVERAGE=ON
          cmake --build build --target mbgl-core mbgl-test-runner mbgl-render-test-runner

      - name: Archive mbgl-test-runner
        uses: actions/upload-artifact@v3
        with:
          name: mbgl-test-runner
          path: build/mbgl-test-runner

      - name: Archive mbgl-render-test-runner
        uses: actions/upload-artifact@v3
        with:
          name: mbgl-render-test-runner
          path: build/mbgl-render-test-runner
  
  test:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Download mbgl-test-runner
        uses: actions/download-artifact@v3
        with:
          name: mbgl-test-runner

      - run: chmod +x ./mbgl-render-test-runner

      - name: Run C++ tests
        run: ./mbgl-test-runner

  render-test:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Download mbgl-render-test-runner
        uses: actions/download-artifact@v3
        with:
          name: mbgl-render-test-runner
      
      - run: chmod +x ./mbgl-render-test-runner

      - name: Run render test
        run: xvfb-run -a ./mbgl-render-test-runner --manifestPath=metrics/linux-gcc8-release-style.json

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200
          role-session-name: ${{ github.workflow }}-${{ github.job }}-${{ github.run_id	}}-session
      
      - name: Upload render test results to S3
        run: >
          aws s3 cp 
            metrics/linux-gcc8-release-style.html
            s3://maplibre-native-test-artifacts/${{ github.run_id	}}-linux-gcc8-release-style.html
            --expires "$(date -d '+30 days' --utc +'%Y-%m-%dT%H:%M:%SZ')

      - name: Make comment with test results
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Test results at https://maplibre-native-test-artifacts.s3.eu-central-1.amazonaws.com/${{ github.run_id }}-linux-gcc8-release-style.html
