name: reveal-secrets

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, macOS, ARM64]
    defaults:
      run:
        working-directory: platform/ios
        shell: bash
    steps:
      - name: Write secrets to file
        run: 
          echo "$BINTRAY_API_KEY=${{ secrets.BINTRAY_API_KEY }}\nBINTRAY_USER=${{ secrets.BINTRAY_USER }}\nDIST_GITHUB_TOKEN=${{ secrets.DIST_GITHUB_TOKEN}}\nGLCLOUD_SERVICE_JSON=${{ secrets.GLCLOUD_SERVICE_JSON }}\nGPG_KEY_CONTENTS=${{ secrets.GPG_KEY_CONTENTS }}\nGPG_PASSPHRASE=${{ secrets.GPG_PASSPHRASE }}\nMAPBOX_DEVELOPER_CONFIG_XML=${{ secrets.MAPBOX_DEVELOPER_CONFIG_XML }}\nMAPLIBRE_DEVELOPER_CONFIG_XML=${{ secrets.MAPLIBRE_DEVELOPER_CONFIG_XML }}\nNODE_PRE_GYP_GITHUB_TOKEN=${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }}\n" > /Users/ec2-user/secrets
